#!/bin/sh

# XRandR — расширение X сервера, позволяющее производить настройки режимов работы мониторов.
# Например, можно изменить разрешение, вывести изображение на внешний монитор,
# повернуть изображение и тому подобное.
# Утилита часто полезна для настройки корректного разрешения при подключении к внешнему монитору или телевизору.
# https://linuxnow.ru/view.php?id=103
#xrandr --output DP1 --auto --right-of LVDS1 &
#
# small tool that allows adjust the brightness of our screen through the console
# https://ubunlog.com/en/adjusting-screen-brightness-with-xbacklight/
xbacklight -set 100 &
#
# утилита для изменения раскладки клавиш клавиатуры и мыши в Xorg.
sysmodmap=/etc/X11/xinit/.Xmodmap
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
#
# system wide .Xresources for our customized dwm is installed by alexxlabs_dwm package
sysresources=/etc/X11/xinit/.Xresources
[[ -f $sysresources ]] && xrdb -merge $sysresources &
#
#feh --bg-fill ~/Pictures/wall/wall.png &
#xset r rate 200 50 &
#
# run bar script and dwm ( do not remove this )
bash /etc/X11/xinit/scripts/bar.sh &
dwm
#
#
# ----------------------------------------------------------
# --------------------- defaults ---------------------------
# ----------------------------------------------------------
#userresources=$HOME/.Xresources
#usermodmap=$HOME/.Xmodmap
#sysresources=/etc/X11/xinit/.Xresources
#sysmodmap=/etc/X11/xinit/.Xmodmap
## merge in defaults and keymaps
#if [ -f $sysresources ]; then
#    xrdb -merge $sysresources
#fi
#if [ -f $sysmodmap ]; then
#    xmodmap $sysmodmap
#fi
#if [ -f "$userresources" ]; then
#    xrdb -merge "$userresources"
#fi
#if [ -f "$usermodmap" ]; then
#    xmodmap "$usermodmap"
#fi
## start some nice programs
#if [ -d /etc/X11/xinit/xinitrc.d ] ; then
# for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#  [ -x "$f" ] && . "$f"
# done
# unset f
#fi
#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login