#!/bin/sh

# !!! NOTE: if we use DisplayManager for login, then we should setup all of this stuff
# !!! in .xprofile - not xinitrc

# XRandR — расширение X сервера, позволяющее производить настройки режимов работы мониторов.
# Например, можно изменить разрешение, вывести изображение на внешний монитор,
# повернуть изображение и тому подобное.
# Утилита часто полезна для настройки корректного разрешения при подключении к внешнему монитору или телевизору.
# https://linuxnow.ru/view.php?id=103
#xrandr --output DP1 --auto --right-of LVDS1 &
#
# small tool that allows adjust the brightness of our screen through the console
# https://ubunlog.com/en/adjusting-screen-brightness-with-xbacklight/
xbacklight -set 100 &
#
# утилита для изменения раскладки клавиш клавиатуры и мыши в Xorg.
sysmodmap=/etc/X11/xinit/.Xmodmap # !!! TODO: setup this file [ now it do not exists ]
[[ -f $sysmodmap ]] && xmodmap $sysmodmap
#
# system wide .Xresources for our customized dwm is installed by alexxlabs_dwm package
sysresources=/etc/X11/xinit/.Xresources
[[ -f $sysresources ]] && xrdb -merge $sysresources &
#
#feh --bg-fill ~/Pictures/wall/wall.png &
#xset r rate 200 50 &
#
# run bar script and dwm ( do not remove this )
/usr/bin/bash /etc/X11/xinit/scripts/bar.sh &
#
dwm
# --------------------------------------------
# ---------======== NOTE EWW =======----------
# --------------------------------------------
# eww is started from dwm config: alexxlabs_dwm/files/dwm/config.def.h
#
# To get started, you'll need to create two files: eww.yuck and eww.scss.
# These files must be placed under $XDG_CONFIG_HOME/eww (this is most likely ~/.config/eww).
# or:
# If you want to separate different widgets even further, you can create a new eww config folder anywhere else.
# Then, you can tell eww to use that configuration directory by passing every command the
# --config /path/to/your/config/dir flag. Make sure to actually include this in all your eww calls,
# including eww kill, eww logs, etc. This launches a separate instance of the eww daemon that has separate logs
# and state from your main eww configuration.
#
# --------------------------------------------
# -------------- defaults --------------------
# --------------------------------------------
#userresources=$HOME/.Xresources
#usermodmap=$HOME/.Xmodmap
#sysresources=/etc/X11/xinit/.Xresources
#sysmodmap=/etc/X11/xinit/.Xmodmap
## merge in defaults and keymaps
#if [ -f $sysresources ]; then
#    xrdb -merge $sysresources
#fi
#if [ -f $sysmodmap ]; then
#    xmodmap $sysmodmap
#fi
#if [ -f "$userresources" ]; then
#    xrdb -merge "$userresources"
#fi
#if [ -f "$usermodmap" ]; then
#    xmodmap "$usermodmap"
#fi
## start some nice programs
#if [ -d /etc/X11/xinit/xinitrc.d ] ; then
# for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
#  [ -x "$f" ] && . "$f"
# done
# unset f
#fi
#twm &
#xclock -geometry 50x50-1+1 &
#xterm -geometry 80x50+494+51 &
#xterm -geometry 80x20+494-0 &
#exec xterm -geometry 80x66+0+0 -name login