#!/bin/sh

exec 2>&1

# With this you can grant permanent access to a specific binary to bind to low-numbered ports via the setcap command:
# requires libcap package (is installed in runtime packages)
#
#setcap CAP_NET_BIND_SERVICE=+eip /usr/local/sbin/asmttpd
# After doing this, /usr/local/asmttpd will be able to bind to low-numbered ports.
# Note that you must use setcap on the binary itself rather than a symlink.

# ${XBPS_DISTDIR} setupped in /etc/env and should be availiable in setupped void VM

exec chpst -u root:root /usr/bin/asmttpd ${XBPS_DISTDIR:-/opt/void-packages}/hostdir/binpkgs 80
